Places = ["Japan", "Canada", "Switzerland", "Turkey", "Malaysia", "South Korea", "Italy"]

print ("Original Order:")
print (Places)
print ("\nAlphabetical Order:")
print (sorted(Places))
print ("\nOriginal Order:")
print (Places)
print ("\nReverse Alphabetical Order:")
print (sorted(Places, reverse = True))
print ("\nOriginal Order:")
print (Places)
print ("\nReversed Order:")
Places.reverse()
print (Places)
print ("\nOriginal Order:")
Places.reverse()
print (Places)
print ("\nAlphabetical Order:")
Places.sort()
print (Places)
print ("\nReverse Alphabetical Order:")
Places.sort(reverse = True)
print (Places)